# Generated by Django 4.0.4 on 2022-05-19 11:35

from django.db import migrations, models
import django.db.models.deletion
import wagtail.blocks
import wagtail.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0069_log_entry_jsonfield'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('navbar', wagtail.fields.StreamField([('navs', wagtail.blocks.StreamBlock([('links', wagtail.blocks.StructBlock([('link', wagtail.blocks.RichTextBlock(features=['link'], required=True)), ('visible', wagtail.blocks.BooleanBlock(default=True, required=False))]))]))], blank=True, null=True, use_json_field=None)),
                ('sidebar', wagtail.fields.StreamField([('sidebar', wagtail.blocks.StructBlock([('title', wagtail.blocks.CharBlock(max_length=250, required=True)), ('links', wagtail.blocks.StreamBlock([('link', wagtail.blocks.StructBlock([('link', wagtail.blocks.RichTextBlock(features=['link'], required=True)), ('visible', wagtail.blocks.BooleanBlock(default=True, required=False))]))]))]))], blank=True, null=True, use_json_field=None)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
